services:
  backend:
    build:
      target: production
    ports:
      - "${BACKEND_PORT:-8080}:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER_PROD}:${POSTGRES_PASSWORD_PROD}@postgres:5432/${POSTGRES_DB_PROD}
      - REDIS_URL=${REDIS_URL}

  frontend:
    build:
      target: production
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "${FRONTEND_PORT:-3001}:3001"

  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PROD:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD:-password}
      POSTGRES_DB: ${POSTGRES_DB_PROD:-cloudnative}
    restart: always
    ports:
      - "${POSTGRES_PORT_PROD:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
