services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"

  backend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER_DEV}:${POSTGRES_PASSWORD_DEV}@postgres:5432/${POSTGRES_DB_DEV}
      - REDIS_URL=${REDIS_URL}
      - MAIL_HOST=${MAIL_HOST}
      - PORT_SMTP=${PORT_SMTP}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_TO=${MAIL_TO}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ../src/backend:/usr/src/app

  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
    ports:
      - "${FRONTEND_PORT:-3001}:3001"
    volumes:
      - ../src/frontend:/usr/src/app

  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DEV:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV:-password}
      POSTGRES_DB: ${POSTGRES_DB_DEV:-cloudnative}
    ports:
      - "${POSTGRES_PORT_DEV:-5433}:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ../database/:/docker-entrypoint-initdb.d/

volumes:
  postgres_data_dev:
  backend:
