bind 0.0.0.0

port 6379

# Activer la persistance avec des snapshots RDB
save 900 1
save 300 10
save 60 10000

appendonly yes
appendfilename "appendonly.aof"

# Définir la limite de mémoire (par exemple, 256 Mo)
maxmemory 256mb

# Politique d'éviction lorsque la limite de mémoire est atteinte
maxmemory-policy allkeys-lru

# Log sur stdout (mieux dans un container)
logfile ""

# Fichier PID (optionnel en container)
pidfile "/var/run/redis/redis.pid"

# Répertoire où Redis stocke les fichiers de données
dir "/data"
